name: Cargo Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - run: cargo build --verbose --release
    - uses: actions/upload-artifact@v7
      with:
        archive: false
        path: target/release/teamviewer-monitor
